name: Deploy
on:
  workflow_dispatch:
  push:
     branches: [ android ]

defaults:
  run:
    shell: bash

env:
  LINK: https://mega.nz/file/RrZHULRS#U5wzv1QD7e9qJFg8ra2zr8ErOyw65N9d3DyIvfwq5ls
  RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_ID: ${{ secrets.TG_ID }}
  TYPE_FILE: apk

jobs:
  process:
    runs-on: ubuntu-latest
    if: github.actor == 'NFS86'
    container:
      image: anggit86/docker:mirrorer

    steps:
      - uses: actions/checkout@v2
      - name: setup config drive
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Download
        run: |
          mega-get ${LINK} $PWD

      - name: Upload
        run: |
          rclone copy --drive-chunk-size 256M --stats 1s $PWD/*.${TYPE_FILE} NFS: -P

      - name: Link Download
        run: |
          LINK_MIRROR=https://nfsproject.projek.workers.dev/1:/$(basename $PWD/*.${TYPE_FILE})
          echo
          echo
          echo Download Link
          echo ========================================
          echo ${LINK_MIRROR}
          echo ========================================
