name: Deploy
on:
  workflow_dispatch:
  push:
     branches: [ android ]

defaults:
  run:
    shell: bash

env:
  LINK: https://mega.nz/file/APg0GLhK#XSkQ6QPXY-lNV_Xs7ps4tw0ko6ktvuXCxrh8G789rhs
  RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_ID: ${{ secrets.TG_ID }}
  TYPE_FILE: apk

jobs:
  process:
    runs-on: ubuntu-latest
    if: github.actor == 'NFS86'
    container:
      image: anggit86/docker:mirrorer

    steps:
      - uses: actions/checkout@v2
      - name: setup config drive
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Download
        run: |
          mega-get ${LINK} $PWD |& tee -a $HOME/download.log || true
          cd $HOME
          curl -F document=@download.log "https://api.telegram.org/bot${TG_TOKEN}/sendDocument" -F chat_id="${TG_ID}" -F "disable_web_page_preview=true" -F "parse_mode=html"

      - name: Upload
        run: |
          rclone copy --drive-chunk-size 256M --stats 1s $PWD/*.${TYPE_FILE} NFS: -P

      - name: Link Download
        run: |
          LINK_MIRROR=https://nfsproject.projek.workers.dev/1:/$(basename $PWD/*.${TYPE_FILE})
          echo ${LINK_MIRROR}
