name: Deploy
on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

env:
  LINK: https://mega.nz/file/fxtkgJ4C#PSWHWFcjdOtNFDkKcNYZUaQ-0Ffep6FNXwFmb0p_E74
  RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
  TYPE_FILE: apk
  GDRIVE_PATH: Game/aduhai

jobs:
  process:
    runs-on: ubuntu-latest
    container:
      image: anggit86/docker:mirrorer

    steps:
      - uses: actions/checkout@v2
      - name: setup config drive
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf

      - name: Download
        run: |
          mega-get ${LINK} $PWD

      - name: Upload
        run: |
          rclone copy --drive-chunk-size 256M --stats 1s $PWD/*.apk NFS:Game/aduhai -P
          Download=https://nfsproject.projek.workers.dev/0:/Game/aduhai/$(basename $PWD/*.${TYPE_FILE})
